# Copyright (c) 2026 Adrian R. Minut
# SPDX-License-Identifier: GPL-3.0

"""Training loop helpers: coroutine loggers, epoch runners, checkpointing."""

from .utils import (
    autoinitcoroutine,
    coro_timer,
    coro_trackavg,
    coro_trackavg_weighted,
    div0,
    mkdirp,
    coro_dict2csv,
)
from .trainutils import (
    deteministic_run,
    check_cuda,
    avgdups,
    apply_batch,
    top5corrects,
    cumentropy,
    cumnll,
    onehot,
    cumbrier,
    coro_epochlog,
    coro_log,
    coro_log_auroc,
    coro_log_timed,
    do_epoch,
    do_trainbatch,
    do_evalbatch,
    bn_update,
    AUROC,
    savecheckpoint,
    loadcheckpoint,
    get_outputsaver,
    summarize_csv,
    group_params_by_layer,
    SummaryWriter,
)

__all__ = [
    "autoinitcoroutine",
    "coro_timer",
    "coro_trackavg",
    "coro_trackavg_weighted",
    "div0",
    "mkdirp",
    "coro_dict2csv",
    "deteministic_run",
    "check_cuda",
    "avgdups",
    "apply_batch",
    "top5corrects",
    "cumentropy",
    "cumnll",
    "onehot",
    "cumbrier",
    "coro_epochlog",
    "coro_log",
    "coro_log_auroc",
    "coro_log_timed",
    "do_epoch",
    "do_trainbatch",
    "do_evalbatch",
    "bn_update",
    "AUROC",
    "savecheckpoint",
    "loadcheckpoint",
    "get_outputsaver",
    "summarize_csv",
    "group_params_by_layer",
    "SummaryWriter",
]
