_target_: vldatasets.standard.DatasetConfig
name: tinyimagenet
outclass: 200
ntrain: 100000
ntest: 10000
insize: 64
train_loader_f: 
  _target_: vldatasets.standard.dataloaders.get_tinyimagenet_train_loaders
  _partial_: true
test_loader_f:
  _target_: vldatasets.standard.dataloaders.get_tinyimagenet_test_loader
  _partial_: true
